services:
    application:
        container_name: tour_bundle_app
        image: richcongress/php:8.1
        volumes:
            - .:/app:rw,cached
            - ~/.composer:/home/application/.composer:cached
            - ~/.ssh:/home/application/.ssh:cached
